-- MySQL Script generated by MySQL Workbench
-- 西元2023年10月06日 (週五) 14時52分18秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capstone_LittleLemonDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capstone_LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capstone_LittleLemonDB` ;
USE `capstone_LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`customers` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `contactNumber` INT NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`staff` (
  `staffID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `annualsalary` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`staffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`orderDelivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`orderDelivery` (
  `orderDeliveryID` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`orderDeliveryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`bookings` (
  `bookingID` INT NOT NULL AUTO_INCREMENT,
  `bookingDate` DATE NOT NULL,
  `bookingSlot` TIME NOT NULL,
  `tableNo` INT NOT NULL,
  `customerID` INT NOT NULL,
  `staffID` INT NOT NULL,
  `orderDeliveryID` INT NOT NULL,
  PRIMARY KEY (`bookingID`),
  INDEX `fk_customerID_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_staffID_idx` (`staffID` ASC) VISIBLE,
  INDEX `fk_orderDeliveryID_idx` (`orderDeliveryID` ASC) VISIBLE,
  CONSTRAINT `fk_customerID`
    FOREIGN KEY (`customerID`)
    REFERENCES `capstone_LittleLemonDB`.`customers` (`customerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staffID`
    FOREIGN KEY (`staffID`)
    REFERENCES `capstone_LittleLemonDB`.`staff` (`staffID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orderDeliveryID`
    FOREIGN KEY (`orderDeliveryID`)
    REFERENCES `capstone_LittleLemonDB`.`orderDelivery` (`orderDeliveryID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`menuItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`menuItem` (
  `itemID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`itemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`menu` (
  `menuID` INT NOT NULL,
  `itemID` INT NOT NULL,
  `cuisine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`menuID`, `itemID`),
  INDEX `fk_itemID_idx` (`itemID` ASC) VISIBLE,
  CONSTRAINT `fk_itemID`
    FOREIGN KEY (`itemID`)
    REFERENCES `capstone_LittleLemonDB`.`menuItem` (`itemID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capstone_LittleLemonDB`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capstone_LittleLemonDB`.`orders` (
  `orderID` INT NOT NULL,
  `menuID` INT NOT NULL,
  `orderDate` DATE NOT NULL,
  `quantity` INT NOT NULL,
  `billAmount` DECIMAL(10,2) NOT NULL,
  `totalCost` DECIMAL(10,2) NOT NULL,
  `bookingID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_bookingID_idx` (`bookingID` ASC) VISIBLE,
  INDEX `fk_menuID_idx` (`menuID` ASC) VISIBLE,
  CONSTRAINT `fk_bookingID`
    FOREIGN KEY (`bookingID`)
    REFERENCES `capstone_LittleLemonDB`.`bookings` (`bookingID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menuID`
    FOREIGN KEY (`menuID`)
    REFERENCES `capstone_LittleLemonDB`.`menu` (`menuID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
